"""Upgrade columns

Revision ID: 949d26e6962a
Revises: f80d6ca25dc7
Create Date: 2024-07-02 17:07:38.669935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949d26e6962a'
down_revision: Union[str, None] = 'f80d6ca25dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'user_id')
    # ### end Alembic commands ###
