"""Add invite

Revision ID: 2df6cb384105
Revises: e6b6a367325f
Create Date: 2024-07-02 15:17:35.443271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2df6cb384105"
down_revision: Union[str, None] = "e6b6a367325f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("members", sa.Column("user", sa.UUID(), nullable=False))
    op.add_column("members", sa.Column("company", sa.UUID(), nullable=False))
    op.drop_constraint("members_user_id_fkey", "members", type_="foreignkey")
    op.drop_constraint("members_company_id_fkey", "members", type_="foreignkey")
    op.create_foreign_key(None, "members", "user", ["user"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "members", "company", ["company"], ["id"], ondelete="CASCADE")
    op.drop_column("members", "user_id")
    op.drop_column("members", "company_id")
    op.drop_column("members", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("id", sa.UUID(), autoincrement=False, nullable=False))
    op.add_column("members", sa.Column("company_id", sa.UUID(), autoincrement=False, nullable=False))
    op.add_column("members", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "members", type_="foreignkey")
    op.drop_constraint(None, "members", type_="foreignkey")
    op.create_foreign_key("members_company_id_fkey", "members", "company", ["company_id"], ["id"])
    op.create_foreign_key("members_user_id_fkey", "members", "user", ["user_id"], ["id"])
    op.drop_column("members", "company")
    op.drop_column("members", "user")
    op.drop_table("invite")
    # ### end Alembic commands ###
