"""Add password in account

Revision ID: ce929e04e6ae
Revises: 949d26e6962a
Create Date: 2024-07-03 11:11:08.660594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce929e04e6ae"
down_revision: Union[str, None] = "949d26e6962a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("password", sa.LargeBinary(), nullable=False))
    op.create_unique_constraint(None, "account", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "account", type_="unique")
    op.drop_column("account", "password")
    # ### end Alembic commands ###
