"""Add unique colums

Revision ID: 7af7f924fc9e
Revises: 95b074e2076d
Create Date: 2024-07-06 11:27:34.987191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7af7f924fc9e'
down_revision: Union[str, None] = '95b074e2076d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['email'])
    op.create_unique_constraint(None, 'company', ['name'])
    op.drop_column('invite', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
