"""Add unique to struct_adm

Revision ID: 70db6695fa5b
Revises: 3c486b0af1fa
Create Date: 2024-07-09 17:17:49.279907

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "70db6695fa5b"
down_revision: Union[str, None] = "3c486b0af1fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_nodes_path", table_name="struct_adm", postgresql_using="gist")
    op.create_unique_constraint(None, "struct_adm", ["name"])
    op.create_unique_constraint(None, "struct_adm", ["path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "struct_adm", type_="unique")
    op.drop_constraint(None, "struct_adm", type_="unique")
    op.create_index("ix_nodes_path", "struct_adm", ["path"], unique=False, postgresql_using="gist")
    # ### end Alembic commands ###
