"""Add task table

Revision ID: 111d91bda36e
Revises: 73576c3ed5ea
Create Date: 2024-07-07 12:14:58.331568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111d91bda36e'
down_revision: Union[str, None] = '73576c3ed5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('responsible_id', sa.UUID(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('execution_time', sa.Interval(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observer',
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('task', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user', 'task')
    )
    op.create_table('performer',
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('task', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user', 'task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performer')
    op.drop_table('observer')
    op.drop_table('task')
    # ### end Alembic commands ###
