"""Upgrade columns

Revision ID: 5e3cf23093c2
Revises: 2df6cb384105
Create Date: 2024-07-02 17:03:07.337462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e3cf23093c2"
down_revision: Union[str, None] = "2df6cb384105"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("account_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "user", "account", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "account_id")
    # ### end Alembic commands ###
