"""Add primary key for position

Revision ID: 73576c3ed5ea
Revises: 7af7f924fc9e
Create Date: 2024-07-06 13:21:49.177178

"""

from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73576c3ed5ea"
down_revision: Union[str, None] = "7af7f924fc9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "struct_adm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("path", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_nodes_path", "struct_adm", ["path"], unique=False, postgresql_using="gist")
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "struct_adm_position",
        sa.Column("struct_adm_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["position.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["struct_adm_id"], ["struct_adm.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("struct_adm_id", "position_id"),
    )
    op.create_table(
        "user_position",
        sa.Column("user", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["position"], ["position.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user", "position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_position")
    op.drop_table("struct_adm_position")
    op.drop_table("position")
    op.drop_index("ix_nodes_path", table_name="struct_adm", postgresql_using="gist")
    op.drop_table("struct_adm")
    # ### end Alembic commands ###
